-dontwarn org.nanohttpd.**
-keep class org.nanohttpd.** { *; }
-dontwarn com.google.gson.**
-keep class com.google.gson.** { *; }
-keep class site.wuzeyu.phonote.NoteEntity { *; }
-keep class site.wuzeyu.phonote.NoteDao { *; }
